# Generated by Django 5.2 on 2025-05-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_fotos/'),
        ),
    ]
