# Generated by Django 5.2 on 2025-05-02 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
